/*
 * Copyright 2019-present Open Networking Foundation
 * Copyright 2019-present, Infosys Limited.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __EnbContextManager__
#define __EnbContextManager__
/******************************************************
* enbContextManager.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.h.tt>
 ***************************************/
#include "memPoolManager.h"

namespace mme
{
	class EnbContext;
	class EnbContextManager
	{
		public:
			/****************************************
			* EnbContextManager
			*  constructor
			****************************************/
			EnbContextManager(int numOfBlocks);
			
			/****************************************
			* EnbContextManager
			*    Destructor
			****************************************/
			~EnbContextManager();
			
			/******************************************
			 * allocateEnbContext
			 * allocate EnbContext data block
			 ******************************************/
			EnbContext* allocateEnbContext();
			
			/******************************************
			 * deallocateEnbContext
			 * deallocate a EnbContext data block
			 ******************************************/
			void deallocateEnbContext(EnbContext* EnbContextp );
	
		private:
			cmn::memPool::MemPoolManager<EnbContext> poolManager_m;
	};
};

#endif
		
		
