/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxPrivateIEs (65535)
#define maxProtocolExtensions (65535)
#define maxProtocolIEs (65535)
#define maxnoofCSGs (256)
#define maxnoofE_RABs (256)
#define maxnoofTAIs (256)
#define maxnoofTACs (256)
#define maxnoofErrors (256)
#define maxnoofBPLMNs (6)
#define maxnoofPLMNsPerMME (32)
#define maxnoofEPLMNs (15)
#define maxnoofEPLMNsPlusOne (16)
#define maxnoofForbLACs (4096)
#define maxnoofForbTACs (4096)
#define maxnoofIndividualS1ConnectionsToReset (256)
#define maxnoofCellsinUEHistoryInfo (16)
#define maxnoofCellsineNB (256)
#define maxnoofTAIforWarning (65535)
#define maxnoofCellID (65535)
#define maxnoofDCNs (32)
#define maxnoofEmergencyAreaID (65535)
#define maxnoofCellinTAI (65535)
#define maxnoofCellinEAI (65535)
#define maxnoofeNBX2TLAs (2)
#define maxnoofeNBX2ExtTLAs (16)
#define maxnoofeNBX2GTPTLAs (16)
#define maxnoofRATs (8)
#define maxnoofGroupIDs (65535)
#define maxnoofMMECs (256)
#define maxnoofCellIDforMDT (32)
#define maxnoofTAforMDT (8)
#define maxnoofMDTPLMNs (16)
#define maxnoofCellsforRestart (256)
#define maxnoofRestartTAIs (2048)
#define maxnoofRestartEmergencyAreaIDs (256)
#define maxEARFCN (262143)
#define maxnoofMBSFNAreaMDT (8)
#define maxnoofRecommendedCells (16)
#define maxnoofRecommendedENBs (16)
#define maxnooftimeperiods (2)
#define maxnoofCellIDforQMC (32)
#define maxnoofTAforQMC (8)
#define maxnoofPLMNforQMC (16)
#define maxnoofBluetoothName (4)
#define maxnoofWLANName (4)
#define maxnoofConnectedengNBs (256)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
