/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_COUNTvaluePDCP_SNlength18_H_
#define	_COUNTvaluePDCP_SNlength18_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDCP-SNlength18.h"
#include "HFNforPDCP-SNlength18.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* COUNTvaluePDCP-SNlength18 */
typedef struct COUNTvaluePDCP_SNlength18 {
	PDCP_SNlength18_t	 pDCP_SNlength18;
	HFNforPDCP_SNlength18_t	 hFNforPDCP_SNlength18;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} COUNTvaluePDCP_SNlength18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_COUNTvaluePDCP_SNlength18;
extern asn_SEQUENCE_specifics_t asn_SPC_COUNTvaluePDCP_SNlength18_specs_1;
extern asn_TYPE_member_t asn_MBR_COUNTvaluePDCP_SNlength18_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _COUNTvaluePDCP_SNlength18_H_ */
#include <asn_internal.h>
