/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "./asn1c/S1AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_CSGMembershipInfo_H_
#define	_CSGMembershipInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CSGMembershipStatus.h"
#include "CSG-Id.h"
#include "CellAccessMode.h"
#include "PLMNidentity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* CSGMembershipInfo */
typedef struct CSGMembershipInfo {
	CSGMembershipStatus_t	 cSGMembershipStatus;
	CSG_Id_t	 cSG_Id;
	CellAccessMode_t	*cellAccessMode;	/* OPTIONAL */
	PLMNidentity_t	*pLMNidentity;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSGMembershipInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSGMembershipInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_CSGMembershipInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_CSGMembershipInfo_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _CSGMembershipInfo_H_ */
#include <asn_internal.h>
