/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_DL_CP_SecurityInformation_H_
#define	_DL_CP_SecurityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DL-NAS-MAC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* DL-CP-SecurityInformation */
typedef struct DL_CP_SecurityInformation {
	DL_NAS_MAC_t	 dl_NAS_MAC;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_CP_SecurityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_CP_SecurityInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_DL_CP_SecurityInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_DL_CP_SecurityInformation_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DL_CP_SecurityInformation_H_ */
#include <asn_internal.h>
