/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_ECGI_List_H_
#define	_ECGI_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EUTRAN_CGI;

/* ECGI-List */
typedef struct ECGI_List {
	A_SEQUENCE_OF(struct EUTRAN_CGI) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECGI_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECGI_List;
extern asn_SET_OF_specifics_t asn_SPC_ECGI_List_specs_1;
extern asn_TYPE_member_t asn_MBR_ECGI_List_1[1];
extern asn_per_constraints_t asn_PER_type_ECGI_List_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ECGI_List_H_ */
#include <asn_internal.h>
