/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_GERAN_Cell_ID_H_
#define	_GERAN_Cell_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LAI.h"
#include "RAC.h"
#include "CI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* GERAN-Cell-ID */
typedef struct GERAN_Cell_ID {
	LAI_t	 lAI;
	RAC_t	 rAC;
	CI_t	 cI;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GERAN_Cell_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GERAN_Cell_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_GERAN_Cell_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_GERAN_Cell_ID_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _GERAN_Cell_ID_H_ */
#include <asn_internal.h>
