/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_Global_GNB_ID_H_
#define	_Global_GNB_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNidentity.h"
#include "GNB-Identity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Global-GNB-ID */
typedef struct Global_GNB_ID {
	PLMNidentity_t	 pLMN_Identity;
	GNB_Identity_t	 gNB_ID;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Global_GNB_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Global_GNB_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_Global_GNB_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_Global_GNB_ID_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Global_GNB_ID_H_ */
#include <asn_internal.h>
