/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_ListeningSubframePattern_H_
#define	_ListeningSubframePattern_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ListeningSubframePattern__pattern_period {
	ListeningSubframePattern__pattern_period_ms1280	= 0,
	ListeningSubframePattern__pattern_period_ms2560	= 1,
	ListeningSubframePattern__pattern_period_ms5120	= 2,
	ListeningSubframePattern__pattern_period_ms10240	= 3
	/*
	 * Enumeration is extensible
	 */
} e_ListeningSubframePattern__pattern_period;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ListeningSubframePattern */
typedef struct ListeningSubframePattern {
	long	 pattern_period;
	long	 pattern_offset;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ListeningSubframePattern_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_pattern_period_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ListeningSubframePattern;
extern asn_SEQUENCE_specifics_t asn_SPC_ListeningSubframePattern_specs_1;
extern asn_TYPE_member_t asn_MBR_ListeningSubframePattern_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ListeningSubframePattern_H_ */
#include <asn_internal.h>
