/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_LoggingDuration_H_
#define	_LoggingDuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoggingDuration {
	LoggingDuration_m10	= 0,
	LoggingDuration_m20	= 1,
	LoggingDuration_m40	= 2,
	LoggingDuration_m60	= 3,
	LoggingDuration_m90	= 4,
	LoggingDuration_m120	= 5
} e_LoggingDuration;

/* LoggingDuration */
typedef long	 LoggingDuration_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LoggingDuration_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LoggingDuration;
extern const asn_INTEGER_specifics_t asn_SPC_LoggingDuration_specs_1;
asn_struct_free_f LoggingDuration_free;
asn_struct_print_f LoggingDuration_print;
asn_constr_check_f LoggingDuration_constraint;
ber_type_decoder_f LoggingDuration_decode_ber;
der_type_encoder_f LoggingDuration_encode_der;
xer_type_decoder_f LoggingDuration_decode_xer;
xer_type_encoder_f LoggingDuration_encode_xer;
oer_type_decoder_f LoggingDuration_decode_oer;
oer_type_encoder_f LoggingDuration_encode_oer;
per_type_decoder_f LoggingDuration_decode_uper;
per_type_encoder_f LoggingDuration_encode_uper;
per_type_decoder_f LoggingDuration_decode_aper;
per_type_encoder_f LoggingDuration_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LoggingDuration_H_ */
#include <asn_internal.h>
