/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_M3period_H_
#define	_M3period_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum M3period {
	M3period_ms100	= 0,
	M3period_ms1000	= 1,
	M3period_ms10000	= 2,
	/*
	 * Enumeration is extensible
	 */
	M3period_ms1024	= 3,
	M3period_ms1280	= 4,
	M3period_ms2048	= 5,
	M3period_ms2560	= 6,
	M3period_ms5120	= 7,
	M3period_ms10240	= 8,
	M3period_min1	= 9
} e_M3period;

/* M3period */
typedef long	 M3period_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_M3period_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_M3period;
extern const asn_INTEGER_specifics_t asn_SPC_M3period_specs_1;
asn_struct_free_f M3period_free;
asn_struct_print_f M3period_print;
asn_constr_check_f M3period_constraint;
ber_type_decoder_f M3period_decode_ber;
der_type_encoder_f M3period_encode_der;
xer_type_decoder_f M3period_decode_xer;
xer_type_encoder_f M3period_encode_xer;
oer_type_decoder_f M3period_decode_oer;
oer_type_encoder_f M3period_encode_oer;
per_type_decoder_f M3period_decode_uper;
per_type_encoder_f M3period_encode_uper;
per_type_decoder_f M3period_decode_aper;
per_type_encoder_f M3period_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _M3period_H_ */
#include <asn_internal.h>
