/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_MutingPatternInformation_H_
#define	_MutingPatternInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MutingPatternInformation__muting_pattern_period {
	MutingPatternInformation__muting_pattern_period_ms0	= 0,
	MutingPatternInformation__muting_pattern_period_ms1280	= 1,
	MutingPatternInformation__muting_pattern_period_ms2560	= 2,
	MutingPatternInformation__muting_pattern_period_ms5120	= 3,
	MutingPatternInformation__muting_pattern_period_ms10240	= 4
	/*
	 * Enumeration is extensible
	 */
} e_MutingPatternInformation__muting_pattern_period;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* MutingPatternInformation */
typedef struct MutingPatternInformation {
	long	 muting_pattern_period;
	long	*muting_pattern_offset;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MutingPatternInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_muting_pattern_period_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MutingPatternInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_MutingPatternInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_MutingPatternInformation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MutingPatternInformation_H_ */
#include <asn_internal.h>
