/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_NB_IoT_PagingTimeWindow_H_
#define	_NB_IoT_PagingTimeWindow_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NB_IoT_PagingTimeWindow {
	NB_IoT_PagingTimeWindow_s1	= 0,
	NB_IoT_PagingTimeWindow_s2	= 1,
	NB_IoT_PagingTimeWindow_s3	= 2,
	NB_IoT_PagingTimeWindow_s4	= 3,
	NB_IoT_PagingTimeWindow_s5	= 4,
	NB_IoT_PagingTimeWindow_s6	= 5,
	NB_IoT_PagingTimeWindow_s7	= 6,
	NB_IoT_PagingTimeWindow_s8	= 7,
	NB_IoT_PagingTimeWindow_s9	= 8,
	NB_IoT_PagingTimeWindow_s10	= 9,
	NB_IoT_PagingTimeWindow_s11	= 10,
	NB_IoT_PagingTimeWindow_s12	= 11,
	NB_IoT_PagingTimeWindow_s13	= 12,
	NB_IoT_PagingTimeWindow_s14	= 13,
	NB_IoT_PagingTimeWindow_s15	= 14,
	NB_IoT_PagingTimeWindow_s16	= 15
	/*
	 * Enumeration is extensible
	 */
} e_NB_IoT_PagingTimeWindow;

/* NB-IoT-PagingTimeWindow */
typedef long	 NB_IoT_PagingTimeWindow_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NB_IoT_PagingTimeWindow_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NB_IoT_PagingTimeWindow;
extern const asn_INTEGER_specifics_t asn_SPC_NB_IoT_PagingTimeWindow_specs_1;
asn_struct_free_f NB_IoT_PagingTimeWindow_free;
asn_struct_print_f NB_IoT_PagingTimeWindow_print;
asn_constr_check_f NB_IoT_PagingTimeWindow_constraint;
ber_type_decoder_f NB_IoT_PagingTimeWindow_decode_ber;
der_type_encoder_f NB_IoT_PagingTimeWindow_encode_der;
xer_type_decoder_f NB_IoT_PagingTimeWindow_decode_xer;
xer_type_encoder_f NB_IoT_PagingTimeWindow_encode_xer;
oer_type_decoder_f NB_IoT_PagingTimeWindow_decode_oer;
oer_type_encoder_f NB_IoT_PagingTimeWindow_encode_oer;
per_type_decoder_f NB_IoT_PagingTimeWindow_decode_uper;
per_type_encoder_f NB_IoT_PagingTimeWindow_encode_uper;
per_type_decoder_f NB_IoT_PagingTimeWindow_decode_aper;
per_type_encoder_f NB_IoT_PagingTimeWindow_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NB_IoT_PagingTimeWindow_H_ */
#include <asn_internal.h>
