/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_NG_eNB_H_
#define	_NG_eNB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Global-ENB-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NG-eNB */
typedef struct NG_eNB {
	Global_ENB_ID_t	 global_ng_eNB_ID;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_eNB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NG_eNB;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_eNB_specs_1;
extern asn_TYPE_member_t asn_MBR_NG_eNB_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NG_eNB_H_ */
#include <asn_internal.h>
