/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_NRrestrictionin5GS_H_
#define	_NRrestrictionin5GS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRrestrictionin5GS {
	NRrestrictionin5GS_nRrestrictedin5GS	= 0
	/*
	 * Enumeration is extensible
	 */
} e_NRrestrictionin5GS;

/* NRrestrictionin5GS */
typedef long	 NRrestrictionin5GS_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRrestrictionin5GS_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRrestrictionin5GS;
extern const asn_INTEGER_specifics_t asn_SPC_NRrestrictionin5GS_specs_1;
asn_struct_free_f NRrestrictionin5GS_free;
asn_struct_print_f NRrestrictionin5GS_print;
asn_constr_check_f NRrestrictionin5GS_constraint;
ber_type_decoder_f NRrestrictionin5GS_decode_ber;
der_type_encoder_f NRrestrictionin5GS_encode_der;
xer_type_decoder_f NRrestrictionin5GS_decode_xer;
xer_type_encoder_f NRrestrictionin5GS_encode_xer;
oer_type_decoder_f NRrestrictionin5GS_decode_oer;
oer_type_encoder_f NRrestrictionin5GS_encode_oer;
per_type_decoder_f NRrestrictionin5GS_decode_uper;
per_type_encoder_f NRrestrictionin5GS_encode_uper;
per_type_decoder_f NRrestrictionin5GS_decode_aper;
per_type_encoder_f NRrestrictionin5GS_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRrestrictionin5GS_H_ */
#include <asn_internal.h>
