/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "./asn1c/S1AP-Containers.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_PrivateIE_Field_H_
#define	_PrivateIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PrivateIE-ID.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PrivateMessageIEs__value_PR {
	PrivateMessageIEs__value_PR_NOTHING	/* No components present */
	
} PrivateMessageIEs__value_PR;

/* PrivateIE-Field */
typedef struct PrivateMessageIEs {
	PrivateIE_ID_t	 id;
	Criticality_t	 criticality;
	struct PrivateMessageIEs__value {
		PrivateMessageIEs__value_PR present;
		union PrivateMessageIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrivateMessageIEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrivateMessageIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_PrivateMessageIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_PrivateMessageIEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PrivateIE_Field_H_ */
#include <asn_internal.h>
