/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "./asn1c/S1AP-Containers.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_ProtocolExtensionContainer_H_
#define	_ProtocolExtensionContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Additional_GUTI_ExtIEs;
struct AllocationAndRetentionPriority_ExtIEs;
struct InformationForCECapableUEs_ExtIEs;
struct AssistanceDataForPaging_ExtIEs;
struct AssistanceDataForRecommendedCells_ExtIEs;
struct Bearers_SubjectToStatusTransfer_ItemExtIEs;
struct BluetoothMeasurementConfiguration_ExtIEs;
struct CancelledCellinEAI_Item_ExtIEs;
struct CancelledCellinTAI_Item_ExtIEs;
struct CellIdentifierAndCELevelForCECapableUEs_ExtIEs;
struct CellID_Broadcast_Item_ExtIEs;
struct CellID_Cancelled_Item_ExtIEs;
struct CellBasedMDT_ExtIEs;
struct CellBasedQMC_ExtIEs;
struct Cdma2000OneXSRVCCInfo_ExtIEs;
struct CellType_ExtIEs;
struct CGI_ExtIEs;
struct CNTypeRestrictions_Item_ExtIEs;
struct ConnectedengNBItem_ExtIEs;
struct CSG_IdList_Item_ExtIEs;
struct COUNTvalue_ExtIEs;
struct COUNTValueExtended_ExtIEs;
struct COUNTvaluePDCP_SNlength18_ExtIEs;
struct CriticalityDiagnostics_ExtIEs;
struct CriticalityDiagnostics_IE_Item_ExtIEs;
struct ServedDCNsItem_ExtIEs;
struct DL_CP_SecurityInformation_ExtIEs;
struct EmergencyAreaID_Broadcast_Item_ExtIEs;
struct EmergencyAreaID_Cancelled_Item_ExtIEs;
struct CompletedCellinEAI_Item_ExtIEs;
struct GERAN_Cell_ID_ExtIEs;
struct GlobalENB_ID_ExtIEs;
struct Global_en_gNB_ID_ExtIEs;
struct ENB_StatusTransfer_TransparentContainer_ExtIEs;
struct EN_DCSONConfigurationTransfer_ExtIEs;
struct EN_DCTransferTypeRequest_ExtIEs;
struct EN_DCTransferTypeReply_ExtIEs;
struct EN_DCSONeNBIdentification_ExtIEs;
struct EN_DCSONengNBIdentification_ExtIEs;
struct E_RABInformationListItem_ExtIEs;
struct E_RABItem_ExtIEs;
struct E_RABQoSParameters_ExtIEs;
struct E_RABUsageReportItem_ExtIEs;
struct EUTRAN_CGI_ExtIEs;
struct ExpectedUEBehaviour_ExtIEs;
struct ExpectedUEActivityBehaviour_ExtIEs;
struct FiveGSTAI_ExtIEs;
struct ForbiddenTAs_Item_ExtIEs;
struct ForbiddenLAs_Item_ExtIEs;
struct GBR_QosInformation_ExtIEs;
struct GUMMEI_ExtIEs;
struct HandoverRestrictionList_ExtIEs;
struct ImmediateMDT_ExtIEs;
struct InformationOnRecommendedCellsAndENBsForPaging_ExtIEs;
struct LAI_ExtIEs;
struct LastVisitedEUTRANCellInformation_ExtIEs;
struct ListeningSubframePattern_ExtIEs;
struct LoggedMDT_ExtIEs;
struct LoggedMBSFNMDT_ExtIEs;
struct M3Configuration_ExtIEs;
struct M4Configuration_ExtIEs;
struct M5Configuration_ExtIEs;
struct M6Configuration_ExtIEs;
struct M7Configuration_ExtIEs;
struct MDT_Configuration_ExtIEs;
struct MBSFN_ResultToLogInfo_ExtIEs;
struct MutingPatternInformation_ExtIEs;
struct NB_IoT_Paging_eDRXInformation_ExtIEs;
struct NR_CGI_ExtIEs;
struct NRUESecurityCapabilities_ExtIEs;
struct PagingAttemptInformation_ExtIEs;
struct Paging_eDRXInformation_ExtIEs;
struct M1PeriodicReporting_ExtIEs;
struct PLMNAreaBasedQMC_ExtIEs;
struct ProSeAuthorized_ExtIEs;
struct PSCellInformation_ExtIEs;
struct RecommendedCellsForPaging_ExtIEs;
struct RecommendedCellsForPagingItem_ExtIEs;
struct RecommendedENBsForPaging_ExtIEs;
struct RecommendedENBItem_ExtIEs;
struct RequestType_ExtIEs;
struct RIMTransfer_ExtIEs;
struct RLFReportInformation_ExtIEs;
struct SecurityContext_ExtIEs;
struct SecondaryRATDataUsageReportItem_ExtIEs;
struct SONInformationReply_ExtIEs;
struct SONConfigurationTransfer_ExtIEs;
struct SynchronisationInformation_ExtIEs;
struct SourceeNB_ID_ExtIEs;
struct SourceeNB_ToTargeteNB_TransparentContainer_ExtIEs;
struct ServedGUMMEIsItem_ExtIEs;
struct Subscription_Based_UE_DifferentiationInfo_ExtIEs;
struct ScheduledCommunicationTime_ExtIEs;
struct SupportedTAs_Item_ExtIEs;
struct TimeSynchronisationInfo_ExtIEs;
struct S_TMSI_ExtIEs;
struct TAIBasedMDT_ExtIEs;
struct TAI_ExtIEs;
struct TAI_Broadcast_Item_ExtIEs;
struct TAI_Cancelled_Item_ExtIEs;
struct TABasedMDT_ExtIEs;
struct TABasedQMC_ExtIEs;
struct TAIBasedQMC_ExtIEs;
struct CompletedCellinTAI_Item_ExtIEs;
struct TargeteNB_ID_ExtIEs;
struct TargetRNC_ID_ExtIEs;
struct TargetNgRanNode_ID_ExtIEs;
struct GNB_ExtIEs;
struct Global_GNB_ID_ExtIEs;
struct NG_eNB_ExtIEs;
struct TargeteNB_ToSourceeNB_TransparentContainer_ExtIEs;
struct M1ThresholdEventA2_ExtIEs;
struct TraceActivation_ExtIEs;
struct Tunnel_Information_ExtIEs;
struct UEAggregate_MaximumBitrates_ExtIEs;
struct UEAppLayerMeasConfig_ExtIEs;
struct UE_S1AP_ID_pair_ExtIEs;
struct UE_associatedLogicalS1_ConnectionItemExtIEs;
struct UESecurityCapabilities_ExtIEs;
struct UE_Sidelink_Aggregate_MaximumBitrates_ExtIEs;
struct UL_CP_SecurityInformation_ExtIEs;
struct UserLocationInformation_ExtIEs;
struct V2XServicesAuthorized_ExtIEs;
struct WLANMeasurementConfiguration_ExtIEs;
struct X2TNLConfigurationInfo_ExtIEs;
struct ENBX2ExtTLA_ExtIEs;
struct E_RABDataForwardingItem_ExtIEs;
struct E_RABToBeSetupItemHOReq_ExtIEs;
struct E_RABAdmittedItem_ExtIEs;
struct E_RABFailedToSetupItemHOReqAckExtIEs;
struct E_RABToBeSwitchedDLItem_ExtIEs;
struct E_RABToBeSwitchedULItem_ExtIEs;
struct E_RABToBeSetupItemBearerSUReqExtIEs;
struct E_RABSetupItemBearerSUResExtIEs;
struct E_RABToBeModifyItemBearerModReqExtIEs;
struct E_RABModifyItemBearerModResExtIEs;
struct E_RABReleaseItemBearerRelCompExtIEs;
struct E_RABToBeSetupItemCtxtSUReqExtIEs;
struct E_RABSetupItemCtxtSUResExtIEs;
struct TAIItemExtIEs;
struct E_RABToBeModifiedItemBearerModInd_ExtIEs;
struct E_RABNotToBeModifiedItemBearerModInd_ExtIEs;
struct CSGMembershipInfo_ExtIEs;
struct E_RABModifyItemBearerModConfExtIEs;
struct E_RABFailedToResumeItemResumeReq_ExtIEs;
struct E_RABFailedToResumeItemResumeRes_ExtIEs;

/* ProtocolExtensionContainer */
typedef struct ProtocolExtensionContainer_180P0 {
	A_SEQUENCE_OF(struct Additional_GUTI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P0_t;
typedef struct ProtocolExtensionContainer_180P1 {
	A_SEQUENCE_OF(struct AllocationAndRetentionPriority_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P1_t;
typedef struct ProtocolExtensionContainer_180P2 {
	A_SEQUENCE_OF(struct InformationForCECapableUEs_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P2_t;
typedef struct ProtocolExtensionContainer_180P3 {
	A_SEQUENCE_OF(struct AssistanceDataForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P3_t;
typedef struct ProtocolExtensionContainer_180P4 {
	A_SEQUENCE_OF(struct AssistanceDataForRecommendedCells_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P4_t;
typedef struct ProtocolExtensionContainer_180P5 {
	A_SEQUENCE_OF(struct Bearers_SubjectToStatusTransfer_ItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P5_t;
typedef struct ProtocolExtensionContainer_180P6 {
	A_SEQUENCE_OF(struct BluetoothMeasurementConfiguration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P6_t;
typedef struct ProtocolExtensionContainer_180P7 {
	A_SEQUENCE_OF(struct CancelledCellinEAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P7_t;
typedef struct ProtocolExtensionContainer_180P8 {
	A_SEQUENCE_OF(struct CancelledCellinTAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P8_t;
typedef struct ProtocolExtensionContainer_180P9 {
	A_SEQUENCE_OF(struct CellIdentifierAndCELevelForCECapableUEs_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P9_t;
typedef struct ProtocolExtensionContainer_180P10 {
	A_SEQUENCE_OF(struct CellID_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P10_t;
typedef struct ProtocolExtensionContainer_180P11 {
	A_SEQUENCE_OF(struct CellID_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P11_t;
typedef struct ProtocolExtensionContainer_180P12 {
	A_SEQUENCE_OF(struct CellBasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P12_t;
typedef struct ProtocolExtensionContainer_180P13 {
	A_SEQUENCE_OF(struct CellBasedQMC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P13_t;
typedef struct ProtocolExtensionContainer_180P14 {
	A_SEQUENCE_OF(struct Cdma2000OneXSRVCCInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P14_t;
typedef struct ProtocolExtensionContainer_180P15 {
	A_SEQUENCE_OF(struct CellType_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P15_t;
typedef struct ProtocolExtensionContainer_180P16 {
	A_SEQUENCE_OF(struct CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P16_t;
typedef struct ProtocolExtensionContainer_180P17 {
	A_SEQUENCE_OF(struct CNTypeRestrictions_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P17_t;
typedef struct ProtocolExtensionContainer_180P18 {
	A_SEQUENCE_OF(struct ConnectedengNBItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P18_t;
typedef struct ProtocolExtensionContainer_180P19 {
	A_SEQUENCE_OF(struct CSG_IdList_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P19_t;
typedef struct ProtocolExtensionContainer_180P20 {
	A_SEQUENCE_OF(struct COUNTvalue_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P20_t;
typedef struct ProtocolExtensionContainer_180P21 {
	A_SEQUENCE_OF(struct COUNTValueExtended_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P21_t;
typedef struct ProtocolExtensionContainer_180P22 {
	A_SEQUENCE_OF(struct COUNTvaluePDCP_SNlength18_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P22_t;
typedef struct ProtocolExtensionContainer_180P23 {
	A_SEQUENCE_OF(struct CriticalityDiagnostics_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P23_t;
typedef struct ProtocolExtensionContainer_180P24 {
	A_SEQUENCE_OF(struct CriticalityDiagnostics_IE_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P24_t;
typedef struct ProtocolExtensionContainer_180P25 {
	A_SEQUENCE_OF(struct ServedDCNsItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P25_t;
typedef struct ProtocolExtensionContainer_180P26 {
	A_SEQUENCE_OF(struct DL_CP_SecurityInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P26_t;
typedef struct ProtocolExtensionContainer_180P27 {
	A_SEQUENCE_OF(struct EmergencyAreaID_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P27_t;
typedef struct ProtocolExtensionContainer_180P28 {
	A_SEQUENCE_OF(struct EmergencyAreaID_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P28_t;
typedef struct ProtocolExtensionContainer_180P29 {
	A_SEQUENCE_OF(struct CompletedCellinEAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P29_t;
typedef struct ProtocolExtensionContainer_180P30 {
	A_SEQUENCE_OF(struct GERAN_Cell_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P30_t;
typedef struct ProtocolExtensionContainer_180P31 {
	A_SEQUENCE_OF(struct GlobalENB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P31_t;
typedef struct ProtocolExtensionContainer_180P32 {
	A_SEQUENCE_OF(struct Global_en_gNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P32_t;
typedef struct ProtocolExtensionContainer_180P33 {
	A_SEQUENCE_OF(struct ENB_StatusTransfer_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P33_t;
typedef struct ProtocolExtensionContainer_180P34 {
	A_SEQUENCE_OF(struct EN_DCSONConfigurationTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P34_t;
typedef struct ProtocolExtensionContainer_180P35 {
	A_SEQUENCE_OF(struct EN_DCTransferTypeRequest_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P35_t;
typedef struct ProtocolExtensionContainer_180P36 {
	A_SEQUENCE_OF(struct EN_DCTransferTypeReply_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P36_t;
typedef struct ProtocolExtensionContainer_180P37 {
	A_SEQUENCE_OF(struct EN_DCSONeNBIdentification_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P37_t;
typedef struct ProtocolExtensionContainer_180P38 {
	A_SEQUENCE_OF(struct EN_DCSONengNBIdentification_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P38_t;
typedef struct ProtocolExtensionContainer_180P39 {
	A_SEQUENCE_OF(struct E_RABInformationListItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P39_t;
typedef struct ProtocolExtensionContainer_180P40 {
	A_SEQUENCE_OF(struct E_RABItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P40_t;
typedef struct ProtocolExtensionContainer_180P41 {
	A_SEQUENCE_OF(struct E_RABQoSParameters_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P41_t;
typedef struct ProtocolExtensionContainer_180P42 {
	A_SEQUENCE_OF(struct E_RABUsageReportItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P42_t;
typedef struct ProtocolExtensionContainer_180P43 {
	A_SEQUENCE_OF(struct EUTRAN_CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P43_t;
typedef struct ProtocolExtensionContainer_180P44 {
	A_SEQUENCE_OF(struct ExpectedUEBehaviour_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P44_t;
typedef struct ProtocolExtensionContainer_180P45 {
	A_SEQUENCE_OF(struct ExpectedUEActivityBehaviour_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P45_t;
typedef struct ProtocolExtensionContainer_180P46 {
	A_SEQUENCE_OF(struct FiveGSTAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P46_t;
typedef struct ProtocolExtensionContainer_180P47 {
	A_SEQUENCE_OF(struct ForbiddenTAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P47_t;
typedef struct ProtocolExtensionContainer_180P48 {
	A_SEQUENCE_OF(struct ForbiddenLAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P48_t;
typedef struct ProtocolExtensionContainer_180P49 {
	A_SEQUENCE_OF(struct GBR_QosInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P49_t;
typedef struct ProtocolExtensionContainer_180P50 {
	A_SEQUENCE_OF(struct GUMMEI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P50_t;
typedef struct ProtocolExtensionContainer_180P51 {
	A_SEQUENCE_OF(struct HandoverRestrictionList_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P51_t;
typedef struct ProtocolExtensionContainer_180P52 {
	A_SEQUENCE_OF(struct ImmediateMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P52_t;
typedef struct ProtocolExtensionContainer_180P53 {
	A_SEQUENCE_OF(struct InformationOnRecommendedCellsAndENBsForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P53_t;
typedef struct ProtocolExtensionContainer_180P54 {
	A_SEQUENCE_OF(struct LAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P54_t;
typedef struct ProtocolExtensionContainer_180P55 {
	A_SEQUENCE_OF(struct LastVisitedEUTRANCellInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P55_t;
typedef struct ProtocolExtensionContainer_180P56 {
	A_SEQUENCE_OF(struct ListeningSubframePattern_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P56_t;
typedef struct ProtocolExtensionContainer_180P57 {
	A_SEQUENCE_OF(struct LoggedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P57_t;
typedef struct ProtocolExtensionContainer_180P58 {
	A_SEQUENCE_OF(struct LoggedMBSFNMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P58_t;
typedef struct ProtocolExtensionContainer_180P59 {
	A_SEQUENCE_OF(struct M3Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P59_t;
typedef struct ProtocolExtensionContainer_180P60 {
	A_SEQUENCE_OF(struct M4Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P60_t;
typedef struct ProtocolExtensionContainer_180P61 {
	A_SEQUENCE_OF(struct M5Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P61_t;
typedef struct ProtocolExtensionContainer_180P62 {
	A_SEQUENCE_OF(struct M6Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P62_t;
typedef struct ProtocolExtensionContainer_180P63 {
	A_SEQUENCE_OF(struct M7Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P63_t;
typedef struct ProtocolExtensionContainer_180P64 {
	A_SEQUENCE_OF(struct MDT_Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P64_t;
typedef struct ProtocolExtensionContainer_180P65 {
	A_SEQUENCE_OF(struct MBSFN_ResultToLogInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P65_t;
typedef struct ProtocolExtensionContainer_180P66 {
	A_SEQUENCE_OF(struct MutingPatternInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P66_t;
typedef struct ProtocolExtensionContainer_180P67 {
	A_SEQUENCE_OF(struct NB_IoT_Paging_eDRXInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P67_t;
typedef struct ProtocolExtensionContainer_180P68 {
	A_SEQUENCE_OF(struct NR_CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P68_t;
typedef struct ProtocolExtensionContainer_180P69 {
	A_SEQUENCE_OF(struct NRUESecurityCapabilities_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P69_t;
typedef struct ProtocolExtensionContainer_180P70 {
	A_SEQUENCE_OF(struct PagingAttemptInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P70_t;
typedef struct ProtocolExtensionContainer_180P71 {
	A_SEQUENCE_OF(struct Paging_eDRXInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P71_t;
typedef struct ProtocolExtensionContainer_180P72 {
	A_SEQUENCE_OF(struct M1PeriodicReporting_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P72_t;
typedef struct ProtocolExtensionContainer_180P73 {
	A_SEQUENCE_OF(struct PLMNAreaBasedQMC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P73_t;
typedef struct ProtocolExtensionContainer_180P74 {
	A_SEQUENCE_OF(struct ProSeAuthorized_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P74_t;
typedef struct ProtocolExtensionContainer_180P75 {
	A_SEQUENCE_OF(struct PSCellInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P75_t;
typedef struct ProtocolExtensionContainer_180P76 {
	A_SEQUENCE_OF(struct RecommendedCellsForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P76_t;
typedef struct ProtocolExtensionContainer_180P77 {
	A_SEQUENCE_OF(struct RecommendedCellsForPagingItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P77_t;
typedef struct ProtocolExtensionContainer_180P78 {
	A_SEQUENCE_OF(struct RecommendedENBsForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P78_t;
typedef struct ProtocolExtensionContainer_180P79 {
	A_SEQUENCE_OF(struct RecommendedENBItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P79_t;
typedef struct ProtocolExtensionContainer_180P80 {
	A_SEQUENCE_OF(struct RequestType_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P80_t;
typedef struct ProtocolExtensionContainer_180P81 {
	A_SEQUENCE_OF(struct RIMTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P81_t;
typedef struct ProtocolExtensionContainer_180P82 {
	A_SEQUENCE_OF(struct RLFReportInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P82_t;
typedef struct ProtocolExtensionContainer_180P83 {
	A_SEQUENCE_OF(struct SecurityContext_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P83_t;
typedef struct ProtocolExtensionContainer_180P84 {
	A_SEQUENCE_OF(struct SecondaryRATDataUsageReportItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P84_t;
typedef struct ProtocolExtensionContainer_180P85 {
	A_SEQUENCE_OF(struct SONInformationReply_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P85_t;
typedef struct ProtocolExtensionContainer_180P86 {
	A_SEQUENCE_OF(struct SONConfigurationTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P86_t;
typedef struct ProtocolExtensionContainer_180P87 {
	A_SEQUENCE_OF(struct SynchronisationInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P87_t;
typedef struct ProtocolExtensionContainer_180P88 {
	A_SEQUENCE_OF(struct SourceeNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P88_t;
typedef struct ProtocolExtensionContainer_180P89 {
	A_SEQUENCE_OF(struct SourceeNB_ToTargeteNB_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P89_t;
typedef struct ProtocolExtensionContainer_180P90 {
	A_SEQUENCE_OF(struct ServedGUMMEIsItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P90_t;
typedef struct ProtocolExtensionContainer_180P91 {
	A_SEQUENCE_OF(struct Subscription_Based_UE_DifferentiationInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P91_t;
typedef struct ProtocolExtensionContainer_180P92 {
	A_SEQUENCE_OF(struct ScheduledCommunicationTime_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P92_t;
typedef struct ProtocolExtensionContainer_180P93 {
	A_SEQUENCE_OF(struct SupportedTAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P93_t;
typedef struct ProtocolExtensionContainer_180P94 {
	A_SEQUENCE_OF(struct TimeSynchronisationInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P94_t;
typedef struct ProtocolExtensionContainer_180P95 {
	A_SEQUENCE_OF(struct S_TMSI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P95_t;
typedef struct ProtocolExtensionContainer_180P96 {
	A_SEQUENCE_OF(struct TAIBasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P96_t;
typedef struct ProtocolExtensionContainer_180P97 {
	A_SEQUENCE_OF(struct TAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P97_t;
typedef struct ProtocolExtensionContainer_180P98 {
	A_SEQUENCE_OF(struct TAI_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P98_t;
typedef struct ProtocolExtensionContainer_180P99 {
	A_SEQUENCE_OF(struct TAI_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P99_t;
typedef struct ProtocolExtensionContainer_180P100 {
	A_SEQUENCE_OF(struct TABasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P100_t;
typedef struct ProtocolExtensionContainer_180P101 {
	A_SEQUENCE_OF(struct TABasedQMC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P101_t;
typedef struct ProtocolExtensionContainer_180P102 {
	A_SEQUENCE_OF(struct TAIBasedQMC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P102_t;
typedef struct ProtocolExtensionContainer_180P103 {
	A_SEQUENCE_OF(struct CompletedCellinTAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P103_t;
typedef struct ProtocolExtensionContainer_180P104 {
	A_SEQUENCE_OF(struct TargeteNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P104_t;
typedef struct ProtocolExtensionContainer_180P105 {
	A_SEQUENCE_OF(struct TargetRNC_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P105_t;
typedef struct ProtocolExtensionContainer_180P106 {
	A_SEQUENCE_OF(struct TargetNgRanNode_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P106_t;
typedef struct ProtocolExtensionContainer_180P107 {
	A_SEQUENCE_OF(struct GNB_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P107_t;
typedef struct ProtocolExtensionContainer_180P108 {
	A_SEQUENCE_OF(struct Global_GNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P108_t;
typedef struct ProtocolExtensionContainer_180P109 {
	A_SEQUENCE_OF(struct NG_eNB_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P109_t;
typedef struct ProtocolExtensionContainer_180P110 {
	A_SEQUENCE_OF(struct TargeteNB_ToSourceeNB_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P110_t;
typedef struct ProtocolExtensionContainer_180P111 {
	A_SEQUENCE_OF(struct M1ThresholdEventA2_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P111_t;
typedef struct ProtocolExtensionContainer_180P112 {
	A_SEQUENCE_OF(struct TraceActivation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P112_t;
typedef struct ProtocolExtensionContainer_180P113 {
	A_SEQUENCE_OF(struct Tunnel_Information_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P113_t;
typedef struct ProtocolExtensionContainer_180P114 {
	A_SEQUENCE_OF(struct UEAggregate_MaximumBitrates_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P114_t;
typedef struct ProtocolExtensionContainer_180P115 {
	A_SEQUENCE_OF(struct UEAppLayerMeasConfig_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P115_t;
typedef struct ProtocolExtensionContainer_180P116 {
	A_SEQUENCE_OF(struct UE_S1AP_ID_pair_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P116_t;
typedef struct ProtocolExtensionContainer_180P117 {
	A_SEQUENCE_OF(struct UE_associatedLogicalS1_ConnectionItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P117_t;
typedef struct ProtocolExtensionContainer_180P118 {
	A_SEQUENCE_OF(struct UESecurityCapabilities_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P118_t;
typedef struct ProtocolExtensionContainer_180P119 {
	A_SEQUENCE_OF(struct UE_Sidelink_Aggregate_MaximumBitrates_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P119_t;
typedef struct ProtocolExtensionContainer_180P120 {
	A_SEQUENCE_OF(struct UL_CP_SecurityInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P120_t;
typedef struct ProtocolExtensionContainer_180P121 {
	A_SEQUENCE_OF(struct UserLocationInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P121_t;
typedef struct ProtocolExtensionContainer_180P122 {
	A_SEQUENCE_OF(struct V2XServicesAuthorized_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P122_t;
typedef struct ProtocolExtensionContainer_180P123 {
	A_SEQUENCE_OF(struct WLANMeasurementConfiguration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P123_t;
typedef struct ProtocolExtensionContainer_180P124 {
	A_SEQUENCE_OF(struct X2TNLConfigurationInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P124_t;
typedef struct ProtocolExtensionContainer_180P125 {
	A_SEQUENCE_OF(struct ENBX2ExtTLA_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P125_t;
typedef struct ProtocolExtensionContainer_180P126 {
	A_SEQUENCE_OF(struct E_RABDataForwardingItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P126_t;
typedef struct ProtocolExtensionContainer_180P127 {
	A_SEQUENCE_OF(struct E_RABToBeSetupItemHOReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P127_t;
typedef struct ProtocolExtensionContainer_180P128 {
	A_SEQUENCE_OF(struct E_RABAdmittedItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P128_t;
typedef struct ProtocolExtensionContainer_180P129 {
	A_SEQUENCE_OF(struct E_RABFailedToSetupItemHOReqAckExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P129_t;
typedef struct ProtocolExtensionContainer_180P130 {
	A_SEQUENCE_OF(struct E_RABToBeSwitchedDLItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P130_t;
typedef struct ProtocolExtensionContainer_180P131 {
	A_SEQUENCE_OF(struct E_RABToBeSwitchedULItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P131_t;
typedef struct ProtocolExtensionContainer_180P132 {
	A_SEQUENCE_OF(struct E_RABToBeSetupItemBearerSUReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P132_t;
typedef struct ProtocolExtensionContainer_180P133 {
	A_SEQUENCE_OF(struct E_RABSetupItemBearerSUResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P133_t;
typedef struct ProtocolExtensionContainer_180P134 {
	A_SEQUENCE_OF(struct E_RABToBeModifyItemBearerModReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P134_t;
typedef struct ProtocolExtensionContainer_180P135 {
	A_SEQUENCE_OF(struct E_RABModifyItemBearerModResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P135_t;
typedef struct ProtocolExtensionContainer_180P136 {
	A_SEQUENCE_OF(struct E_RABReleaseItemBearerRelCompExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P136_t;
typedef struct ProtocolExtensionContainer_180P137 {
	A_SEQUENCE_OF(struct E_RABToBeSetupItemCtxtSUReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P137_t;
typedef struct ProtocolExtensionContainer_180P138 {
	A_SEQUENCE_OF(struct E_RABSetupItemCtxtSUResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P138_t;
typedef struct ProtocolExtensionContainer_180P139 {
	A_SEQUENCE_OF(struct TAIItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P139_t;
typedef struct ProtocolExtensionContainer_180P140 {
	A_SEQUENCE_OF(struct E_RABToBeModifiedItemBearerModInd_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P140_t;
typedef struct ProtocolExtensionContainer_180P141 {
	A_SEQUENCE_OF(struct E_RABNotToBeModifiedItemBearerModInd_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P141_t;
typedef struct ProtocolExtensionContainer_180P142 {
	A_SEQUENCE_OF(struct CSGMembershipInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P142_t;
typedef struct ProtocolExtensionContainer_180P143 {
	A_SEQUENCE_OF(struct E_RABModifyItemBearerModConfExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P143_t;
typedef struct ProtocolExtensionContainer_180P144 {
	A_SEQUENCE_OF(struct E_RABFailedToResumeItemResumeReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P144_t;
typedef struct ProtocolExtensionContainer_180P145 {
	A_SEQUENCE_OF(struct E_RABFailedToResumeItemResumeRes_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_180P145_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P54;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P54_109[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P55;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P55_111[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P56;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P56_113[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P57;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P57_115[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P58;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P58_117[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P59;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P59_119[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P60;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P60_121[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P61;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P61_123[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P62;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P62_125[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P63;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P63_127[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P64;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P64_129[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P65;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P65_131[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P66;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P66_133[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P67;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P67_135[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P68;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P68_137[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P69;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P69_139[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P70;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P70_141[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P71;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P71_143[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P72;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P72_145[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P73;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P73_147[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P74;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P74_149[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P75;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P75_151[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P76;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P76_specs_153;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P76_153[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P77;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P77_specs_155;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P77_155[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P78;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P78_specs_157;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P78_157[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P79;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P79_specs_159;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P79_159[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P80;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P80_specs_161;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P80_161[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P81;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P81_specs_163;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P81_163[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P82;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P82_specs_165;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P82_165[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P83;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P83_specs_167;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P83_167[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P84;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P84_specs_169;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P84_169[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P85;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P85_specs_171;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P85_171[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P86;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P86_specs_173;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P86_173[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P87;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P87_specs_175;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P87_175[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P88;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P88_specs_177;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P88_177[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P89;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P89_specs_179;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P89_179[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P90;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P90_specs_181;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P90_181[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P91;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P91_specs_183;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P91_183[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P92;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P92_specs_185;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P92_185[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P93;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P93_specs_187;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P93_187[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P94;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P94_specs_189;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P94_189[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P95;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P95_specs_191;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P95_191[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P96;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P96_specs_193;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P96_193[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P97;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P97_specs_195;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P97_195[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P98;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P98_specs_197;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P98_197[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P99;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P99_specs_199;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P99_199[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P100;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P100_specs_201;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P100_201[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P101;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P101_specs_203;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P101_203[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P101_constr_203;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P102;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P102_specs_205;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P102_205[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P102_constr_205;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P103;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P103_specs_207;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P103_207[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P103_constr_207;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P104;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P104_specs_209;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P104_209[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P104_constr_209;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P105;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P105_specs_211;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P105_211[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P105_constr_211;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P106;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P106_specs_213;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P106_213[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P106_constr_213;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P107;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P107_specs_215;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P107_215[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P107_constr_215;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P108;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P108_specs_217;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P108_217[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P108_constr_217;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P109;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P109_specs_219;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P109_219[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P109_constr_219;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P110;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P110_specs_221;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P110_221[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P110_constr_221;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P111;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P111_specs_223;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P111_223[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P111_constr_223;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P112;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P112_specs_225;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P112_225[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P112_constr_225;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P113;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P113_specs_227;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P113_227[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P113_constr_227;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P114;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P114_specs_229;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P114_229[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P114_constr_229;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P115;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P115_specs_231;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P115_231[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P115_constr_231;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P116;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P116_specs_233;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P116_233[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P116_constr_233;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P117;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P117_specs_235;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P117_235[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P117_constr_235;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P118;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P118_specs_237;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P118_237[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P118_constr_237;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P119;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P119_specs_239;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P119_239[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P119_constr_239;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P120;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P120_specs_241;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P120_241[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P120_constr_241;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P121;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P121_specs_243;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P121_243[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P121_constr_243;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P122;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P122_specs_245;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P122_245[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P122_constr_245;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P123;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P123_specs_247;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P123_247[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P123_constr_247;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P124;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P124_specs_249;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P124_249[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P124_constr_249;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P125;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P125_specs_251;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P125_251[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P125_constr_251;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P126;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P126_specs_253;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P126_253[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P126_constr_253;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P127;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P127_specs_255;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P127_255[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P127_constr_255;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P128;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P128_specs_257;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P128_257[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P128_constr_257;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P129;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P129_specs_259;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P129_259[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P129_constr_259;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P130;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P130_specs_261;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P130_261[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P130_constr_261;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P131;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P131_specs_263;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P131_263[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P131_constr_263;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P132;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P132_specs_265;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P132_265[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P132_constr_265;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P133;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P133_specs_267;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P133_267[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P133_constr_267;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P134;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P134_specs_269;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P134_269[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P134_constr_269;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P135;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P135_specs_271;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P135_271[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P135_constr_271;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P136;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P136_specs_273;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P136_273[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P136_constr_273;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P137;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P137_specs_275;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P137_275[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P137_constr_275;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P138;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P138_specs_277;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P138_277[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P138_constr_277;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P139;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P139_specs_279;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P139_279[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P139_constr_279;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P140;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P140_specs_281;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P140_281[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P140_constr_281;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P141;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P141_specs_283;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P141_283[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P141_constr_283;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P142;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P142_specs_285;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P142_285[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P142_constr_285;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P143;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P143_specs_287;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P143_287[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P143_constr_287;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P144;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P144_specs_289;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P144_289[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P144_constr_289;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_180P145;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_180P145_specs_291;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_180P145_291[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_180P145_constr_291;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolExtensionContainer_H_ */
#include <asn_internal.h>
