/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_PS_ServiceNotAvailable_H_
#define	_PS_ServiceNotAvailable_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PS_ServiceNotAvailable {
	PS_ServiceNotAvailable_ps_service_not_available	= 0
	/*
	 * Enumeration is extensible
	 */
} e_PS_ServiceNotAvailable;

/* PS-ServiceNotAvailable */
typedef long	 PS_ServiceNotAvailable_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PS_ServiceNotAvailable_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PS_ServiceNotAvailable;
extern const asn_INTEGER_specifics_t asn_SPC_PS_ServiceNotAvailable_specs_1;
asn_struct_free_f PS_ServiceNotAvailable_free;
asn_struct_print_f PS_ServiceNotAvailable_print;
asn_constr_check_f PS_ServiceNotAvailable_constraint;
ber_type_decoder_f PS_ServiceNotAvailable_decode_ber;
der_type_encoder_f PS_ServiceNotAvailable_encode_der;
xer_type_decoder_f PS_ServiceNotAvailable_decode_xer;
xer_type_encoder_f PS_ServiceNotAvailable_encode_xer;
oer_type_decoder_f PS_ServiceNotAvailable_decode_oer;
oer_type_encoder_f PS_ServiceNotAvailable_encode_oer;
per_type_decoder_f PS_ServiceNotAvailable_decode_uper;
per_type_encoder_f PS_ServiceNotAvailable_encode_uper;
per_type_decoder_f PS_ServiceNotAvailable_decode_aper;
per_type_encoder_f PS_ServiceNotAvailable_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PS_ServiceNotAvailable_H_ */
#include <asn_internal.h>
