/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_ReportIntervalMDT_H_
#define	_ReportIntervalMDT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportIntervalMDT {
	ReportIntervalMDT_ms120	= 0,
	ReportIntervalMDT_ms240	= 1,
	ReportIntervalMDT_ms480	= 2,
	ReportIntervalMDT_ms640	= 3,
	ReportIntervalMDT_ms1024	= 4,
	ReportIntervalMDT_ms2048	= 5,
	ReportIntervalMDT_ms5120	= 6,
	ReportIntervalMDT_ms10240	= 7,
	ReportIntervalMDT_min1	= 8,
	ReportIntervalMDT_min6	= 9,
	ReportIntervalMDT_min12	= 10,
	ReportIntervalMDT_min30	= 11,
	ReportIntervalMDT_min60	= 12
} e_ReportIntervalMDT;

/* ReportIntervalMDT */
typedef long	 ReportIntervalMDT_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ReportIntervalMDT_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ReportIntervalMDT;
extern const asn_INTEGER_specifics_t asn_SPC_ReportIntervalMDT_specs_1;
asn_struct_free_f ReportIntervalMDT_free;
asn_struct_print_f ReportIntervalMDT_print;
asn_constr_check_f ReportIntervalMDT_constraint;
ber_type_decoder_f ReportIntervalMDT_decode_ber;
der_type_encoder_f ReportIntervalMDT_encode_der;
xer_type_decoder_f ReportIntervalMDT_decode_xer;
xer_type_encoder_f ReportIntervalMDT_encode_xer;
oer_type_decoder_f ReportIntervalMDT_decode_oer;
oer_type_encoder_f ReportIntervalMDT_encode_oer;
per_type_decoder_f ReportIntervalMDT_decode_uper;
per_type_encoder_f ReportIntervalMDT_encode_uper;
per_type_decoder_f ReportIntervalMDT_decode_aper;
per_type_encoder_f ReportIntervalMDT_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportIntervalMDT_H_ */
#include <asn_internal.h>
