/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_SONInformationReport_H_
#define	_SONInformationReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SONInformationReport_PR {
	SONInformationReport_PR_NOTHING,	/* No components present */
	SONInformationReport_PR_rLFReportInformation
	/* Extensions may appear below */
	
} SONInformationReport_PR;

/* Forward declarations */
struct RLFReportInformation;

/* SONInformationReport */
typedef struct SONInformationReport {
	SONInformationReport_PR present;
	union SONInformationReport_u {
		struct RLFReportInformation	*rLFReportInformation;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SONInformationReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SONInformationReport;
extern asn_CHOICE_specifics_t asn_SPC_SONInformationReport_specs_1;
extern asn_TYPE_member_t asn_MBR_SONInformationReport_1[1];
extern asn_per_constraints_t asn_PER_type_SONInformationReport_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SONInformationReport_H_ */
#include <asn_internal.h>
