/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "./asn1c/S1AP-IEs.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -gen-PER -findirect-choice -pdu=S1AP-PDU`
 */

#ifndef	_TargetRNC_ID_H_
#define	_TargetRNC_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LAI.h"
#include "RAC.h"
#include "RNC-ID.h"
#include "ExtendedRNC-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* TargetRNC-ID */
typedef struct TargetRNC_ID {
	LAI_t	 lAI;
	RAC_t	*rAC;	/* OPTIONAL */
	RNC_ID_t	 rNC_ID;
	ExtendedRNC_ID_t	*extendedRNC_ID;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TargetRNC_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TargetRNC_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_TargetRNC_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_TargetRNC_ID_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _TargetRNC_ID_H_ */
#include <asn_internal.h>
