 /*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */ 
/******************************************************************************
 * enbContextManager.cpp
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.cpp.tt>
 ******************************************************************************/

#include "memPoolManager.h"
#include "contextManager/dataBlocks.h"
#include "contextManager/enbContextManager.h"

using namespace cmn::memPool;

namespace mme
{
	/******************************************************************************
	* Constructor
	******************************************************************************/
	EnbContextManager::EnbContextManager(int numOfBlocks):poolManager_m(numOfBlocks)
	{
	}
	
	/******************************************************************************
	* Destructor
	******************************************************************************/
	EnbContextManager::~EnbContextManager()
	{
	}
	
	/******************************************************************************
	* Allocate EnbContext data block
	******************************************************************************/
	EnbContext* EnbContextManager::allocateEnbContext()
	{
		EnbContext* EnbContext_p = poolManager_m.allocate();
		return EnbContext_p;
	}
	
	/******************************************************************************
	* Deallocate a EnbContext data block
	******************************************************************************/
	void EnbContextManager::deallocateEnbContext(EnbContext* EnbContextp )
	{
		poolManager_m.free( EnbContextp );
	}
}